"""Application constants and configuration"""

# Available seasons
SEASONS = list(range(2016, 2026))

# Last season in list
CURRENT_SEASON = max(SEASONS)

# Top-level cache names (used by App.caches)
CACHE = {
    "STATISTICS": "Statistics",
    "DEPTH_CHART": "ESPNDepthChart",
    "SCHEDULES": "Schedules",
}

# Statistics cache keys
STATS = {
    "ALL_PLAYERS": "all_players",
    "BY_YEAR": "by_year",
    "PLAYER_WEEKLY_STATS": "player_weekly_stats",
}

# Important fantasy skill positions
POSITIONS = ['QB', 'RB', 'WR', 'TE']

# Team abbreviations
TEAMS = ["ARI", "ATL", "BAL", "BUF", "CAR", "CHI", "CIN", "CLE", 
         "DAL", "DEN", "DET", "GB" , "HOU", "IND", "JAX", "KC" , 
         "LV" , "LAC", "LAR", "MIA", "MIN", "NE" , "NO" , "NYG", 
         "NYJ", "PHI", "PIT", "SF" , "SEA", "TB" , "TEN", "WSH"]

# Normalize historical/alternate abbreviations to canonical team codes.
TEAM_ABBR_NORMALIZATION = {
    "LA": "LAR",
    "STL": "LAR",
    "WAS": "WSH",
    "OAK": "LV",
    "SD": "LAC",
    "JAC": "JAX",
}

# NFL Division Structure
NFL_DIVISIONS = {
    "AFC": {
        "North": ["BAL", "CIN", "CLE", "PIT"],
        "South": ["HOU", "IND", "JAX", "TEN"],
        "East": ["BUF", "MIA", "NE", "NYJ"],
        "West": ["DEN", "KC", "LV", "LAC"]
    },
    "NFC": {
        "North": ["CHI", "DET", "GB", "MIN"],
        "South": ["ATL", "CAR", "NO", "TB"],
        "East": ["DAL", "NYG", "PHI", "WSH"],
        "West": ["ARI", "LAR", "SF", "SEA"]
    }
}

# Team display names
TEAM_NAMES = {
    "ARI": "Arizona Cardinals", "ATL": "Atlanta Falcons", "BAL": "Baltimore Ravens",
    "BUF": "Buffalo Bills", "CAR": "Carolina Panthers", "CHI": "Chicago Bears",
    "CIN": "Cincinnati Bengals", "CLE": "Cleveland Browns", "DAL": "Dallas Cowboys",
    "DEN": "Denver Broncos", "DET": "Detroit Lions", "GB": "Green Bay Packers",
    "HOU": "Houston Texans", "IND": "Indianapolis Colts", "JAX": "Jacksonville Jaguars",
    "KC": "Kansas City Chiefs", "LAC": "Los Angeles Chargers", "LAR": "Los Angeles Rams",
    "LV": "Las Vegas Raiders", "MIA": "Miami Dolphins", "MIN": "Minnesota Vikings",
    "NE": "New England Patriots", "NO": "New Orleans Saints", "NYG": "New York Giants",
    "NYJ": "New York Jets", "PHI": "Philadelphia Eagles", "PIT": "Pittsburgh Steelers",
    "SF": "San Francisco 49ers", "SEA": "Seattle Seahawks", "TB": "Tampa Bay Buccaneers",
    "TEN": "Tennessee Titans", "WSH": "Washington Commanders"
}

PLAYER_WEEKLY_COLUMN_MAP = {
    "season": "season",
    "week": "week",
    "game_id": "game_id",
    "player_id": "player_id",
    "player_name": "player_name",
    "player_display_name": "player_display_name",
    "position": "position",
    "position_group": "position_group",
    "team": "team",
    "opponent_team": "opponent_team",
    "completions": "completions",
    "attempts": "attempts",
    "passing_yards": "passing_yards",
    "passing_tds": "passing_tds",
    "passing_interceptions": "passing_interceptions",
    "sacks_suffered": "sacks_suffered",
    "sack_yards_lost": "sack_yards_lost",
    "sack_fumbles": "sack_fumbles",
    "sack_fumbles_lost": "sack_fumbles_lost",
    "passing_air_yards": "passing_air_yards",
    "passing_yards_after_catch": "passing_yards_after_catch",
    "passing_first_downs": "passing_first_downs",
    "passing_epa": "passing_epa",
    "passing_cpoe": "passing_cpoe",
    "passing_2pt_conversions": "passing_2pt_conversions",
    "pacr": "pacr",
    "carries": "carries",
    "rushing_yards": "rushing_yards",
    "rushing_tds": "rushing_tds",
    "rushing_fumbles": "rushing_fumbles",
    "rushing_fumbles_lost": "rushing_fumbles_lost",
    "rushing_first_downs": "rushing_first_downs",
    "rushing_epa": "rushing_epa",
    "rushing_2pt_conversions": "rushing_2pt_conversions",
    "receptions": "receptions",
    "targets": "targets",
    "receiving_yards": "receiving_yards",
    "receiving_tds": "receiving_tds",
    "receiving_fumbles": "receiving_fumbles",
    "receiving_fumbles_lost": "receiving_fumbles_lost",
    "receiving_air_yards": "receiving_air_yards",
    "receiving_yards_after_catch": "receiving_yards_after_catch",
    "receiving_first_downs": "receiving_first_downs",
    "receiving_epa": "receiving_epa",
    "receiving_2pt_conversions": "receiving_2pt_conversions",
    "racr": "racr",
    "target_share": "target_share",
    "air_yards_share": "air_yards_share",
    "wopr": "wopr",
    "misc_yards": "misc_yards",
    "fumble_recovery_own": "fumble_recovery_own",
    "fumble_recovery_yards_own": "fumble_recovery_yards_own",
    "fumble_recovery_opp": "fumble_recovery_opp",
    "fumble_recovery_yards_opp": "fumble_recovery_yards_opp",
    "fumble_recovery_tds": "fumble_recovery_tds",
    "penalties": "penalties",
    "penalty_yards": "penalty_yards",
    "punt_returns": "punt_returns",
    "punt_return_yards": "punt_return_yards",
    "kickoff_returns": "kickoff_returns",
    "kickoff_return_yards": "kickoff_return_yards",
    "fantasy_points": "fantasy_points",
    "fantasy_points_ppr": "fantasy_points_ppr",
}

PLAYER_SEASONAL_COLUMN_MAP = {
    "season": "season",
    "player_id": "player_id",
    "player_name": "player_name",
    "player_display_name": "player_display_name",
    "position": "position",
    "position_group": "position_group",
    "team": "team",
    "completions": "completions",
    "attempts": "attempts",
    "passing_yards": "passing_yards",
    "passing_tds": "passing_tds",
    "passing_interceptions": "passing_interceptions",
    "sacks_suffered": "sacks_suffered",
    "sack_yards_lost": "sack_yards_lost",
    "sack_fumbles": "sack_fumbles",
    "sack_fumbles_lost": "sack_fumbles_lost",
    "passing_air_yards": "passing_air_yards",
    "passing_yards_after_catch": "passing_yards_after_catch",
    "passing_first_downs": "passing_first_downs",
    "passing_epa": "passing_epa",
    "passing_cpoe": "passing_cpoe",
    "passing_2pt_conversions": "passing_2pt_conversions",
    "pacr": "pacr",
    "carries": "carries",
    "rushing_yards": "rushing_yards",
    "rushing_tds": "rushing_tds",
    "rushing_fumbles": "rushing_fumbles",
    "rushing_fumbles_lost": "rushing_fumbles_lost",
    "rushing_first_downs": "rushing_first_downs",
    "rushing_epa": "rushing_epa",
    "rushing_2pt_conversions": "rushing_2pt_conversions",
    "receptions": "receptions",
    "targets": "targets",
    "receiving_yards": "receiving_yards",
    "receiving_tds": "receiving_tds",
    "receiving_fumbles": "receiving_fumbles",
    "receiving_fumbles_lost": "receiving_fumbles_lost",
    "receiving_air_yards": "receiving_air_yards",
    "receiving_yards_after_catch": "receiving_yards_after_catch",
    "receiving_first_downs": "receiving_first_downs",
    "receiving_epa": "receiving_epa",
    "receiving_2pt_conversions": "receiving_2pt_conversions",
    "racr": "racr",
    "target_share": "target_share",
    "air_yards_share": "air_yards_share",
    "wopr": "wopr",
    "misc_yards": "misc_yards",
    "fumble_recovery_own": "fumble_recovery_own",
    "fumble_recovery_yards_own": "fumble_recovery_yards_own",
    "fumble_recovery_opp": "fumble_recovery_opp",
    "fumble_recovery_yards_opp": "fumble_recovery_yards_opp",
    "fumble_recovery_tds": "fumble_recovery_tds",
    "penalties": "penalties",
    "penalty_yards": "penalty_yards",
    "punt_returns": "punt_returns",
    "punt_return_yards": "punt_return_yards",
    "kickoff_returns": "kickoff_returns",
    "kickoff_return_yards": "kickoff_return_yards",
    "fantasy_points": "fantasy_points",
    "fantasy_points_ppr": "fantasy_points_ppr",
}

FF_OPP_WEEKLY_COLUMN_MAP = {
    "season": "season",
    "week": "week",
    "game_id": "game_id",
    "player_id": "player_id",
    "player_display_name": "player_display_name",
    "position": "position",
    "team": "team",
    "pass_attempt": "ffo_pass_att",
    "rec_attempt": "ffo_rec_att",
    "rush_attempt": "ffo_rush_att",
    "pass_air_yards": "ffo_pass_air_yds",
    "rec_air_yards": "ffo_rec_air_yds",
    "pass_completions": "ffo_pass_cmp",
    "receptions": "ffo_rec",
    "pass_completions_exp": "ffo_pass_cmp_exp",
    "receptions_exp": "ffo_rec_exp",
    "pass_yards_gained": "ffo_pass_yds_gained",
    "rec_yards_gained": "ffo_rec_yds_gained",
    "rush_yards_gained": "ffo_rush_yds_gained",
    "pass_yards_gained_exp": "ffo_pass_yds_gained_exp",
    "rec_yards_gained_exp": "ffo_rec_yds_gained_exp",
    "rush_yards_gained_exp": "ffo_rush_yds_gained_exp",
    "pass_touchdown": "ffo_pass_td",
    "rec_touchdown": "ffo_rec_td",
    "rush_touchdown": "ffo_rush_td",
    "pass_touchdown_exp": "ffo_pass_td_exp",
    "rec_touchdown_exp": "ffo_rec_td_exp",
    "rush_touchdown_exp": "ffo_rush_td_exp",
    "pass_two_point_conv": "ffo_pass_2pt",
    "rec_two_point_conv": "ffo_rec_2pt",
    "rush_two_point_conv": "ffo_rush_2pt",
    "pass_two_point_conv_exp": "ffo_pass_2pt_exp",
    "rec_two_point_conv_exp": "ffo_rec_2pt_exp",
    "rush_two_point_conv_exp": "ffo_rush_2pt_exp",
    "pass_first_down": "ffo_pass_fd",
    "rec_first_down": "ffo_rec_fd",
    "rush_first_down": "ffo_rush_fd",
    "pass_first_down_exp": "ffo_pass_fd_exp",
    "rec_first_down_exp": "ffo_rec_fd_exp",
    "rush_first_down_exp": "ffo_rush_fd_exp",
    "pass_interception": "ffo_pass_int",
    "rec_interception": "ffo_rec_int",
    "pass_interception_exp": "ffo_pass_int_exp",
    "rec_interception_exp": "ffo_rec_int_exp",
    "rec_fumble_lost": "ffo_rec_fumble_lost",
    "rush_fumble_lost": "ffo_rush_fumble_lost",
    "pass_fantasy_points_exp": "ffo_pass_fp_exp",
    "rec_fantasy_points_exp": "ffo_rec_fp_exp",
    "rush_fantasy_points_exp": "ffo_rush_fp_exp",
    "pass_fantasy_points": "ffo_pass_fp",
    "rec_fantasy_points": "ffo_rec_fp",
    "rush_fantasy_points": "ffo_rush_fp",
    "total_yards_gained": "ffo_total_yds_gained",
    "total_yards_gained_exp": "ffo_total_yds_gained_exp",
    "total_touchdown": "ffo_total_td",
    "total_touchdown_exp": "ffo_total_td_exp",
    "total_first_down": "ffo_total_fd",
    "total_first_down_exp": "ffo_total_fd_exp",
    "total_fantasy_points": "ffo_total_fp",
    "total_fantasy_points_exp": "ffo_total_fp_exp",
    "pass_completions_diff": "ffo_pass_cmp_diff",
    "receptions_diff": "ffo_rec_diff",
    "pass_yards_gained_diff": "ffo_pass_yds_gained_diff",
    "rec_yards_gained_diff": "ffo_rec_yds_gained_diff",
    "rush_yards_gained_diff": "ffo_rush_yds_gained_diff",
    "pass_touchdown_diff": "ffo_pass_td_diff",
    "rec_touchdown_diff": "ffo_rec_td_diff",
    "rush_touchdown_diff": "ffo_rush_td_diff",
    "pass_two_point_conv_diff": "ffo_pass_2pt_diff",
    "rec_two_point_conv_diff": "ffo_rec_2pt_diff",
    "rush_two_point_conv_diff": "ffo_rush_2pt_diff",
    "pass_first_down_diff": "ffo_pass_fd_diff",
    "rec_first_down_diff": "ffo_rec_fd_diff",
    "rush_first_down_diff": "ffo_rush_fd_diff",
    "pass_interception_diff": "ffo_pass_int_diff",
    "rec_interception_diff": "ffo_rec_int_diff",
    "pass_fantasy_points_diff": "ffo_pass_fp_diff",
    "rec_fantasy_points_diff": "ffo_rec_fp_diff",
    "rush_fantasy_points_diff": "ffo_rush_fp_diff",
    "total_yards_gained_diff": "ffo_total_yds_gained_diff",
    "total_touchdown_diff": "ffo_total_td_diff",
    "total_first_down_diff": "ffo_total_fd_diff",
    "total_fantasy_points_diff": "ffo_total_fp_diff",
}

NEXTGEN_PASS_COLUMN_MAP = {
    "season": "season",
    "week": "week",
    "player_display_name": "player_display_name",
    "position": "position",
    "team": "team",
    "player_gsis_id": "ng_pass_player_gsis_id",
    "avg_time_to_throw": "ng_pass_avg_time_to_throw",
    "avg_completed_air_yards": "ng_pass_avg_completed_air_yds",
    "avg_intended_air_yards": "ng_pass_avg_intended_air_yds",
    "avg_air_yards_differential": "ng_pass_avg_air_yds_diff",
    "aggressiveness": "ng_pass_aggressiveness",
    "max_completed_air_distance": "ng_pass_max_completed_air_distance",
    "avg_air_yards_to_sticks": "ng_pass_avg_air_yds_to_sticks",
    "attempts": "ng_pass_att",
    "pass_yards": "ng_pass_pass_yds",
    "pass_touchdowns": "ng_pass_pass_td",
    "interceptions": "ng_pass_int",
    "passer_rating": "ng_pass_passer_rating",
    "completions": "ng_pass_cmp",
    "completion_percentage": "ng_pass_cmp_pct",
    "expected_completion_percentage": "ng_pass_exp_cmp_pct",
    "completion_percentage_above_expectation": "ng_pass_cmp_pct_above_expectation",
    "avg_air_distance": "ng_pass_avg_air_distance",
    "max_air_distance": "ng_pass_max_air_distance",
}

NEXTGEN_REC_COLUMN_MAP = {
    "season": "season",
    "week": "week",
    "player_display_name": "player_display_name",
    "position": "position",
    "team": "team",
    "player_gsis_id": "ng_rec_player_gsis_id",
    "avg_cushion": "ng_rec_avg_cushion",
    "avg_separation": "ng_rec_avg_separation",
    "avg_intended_air_yards": "ng_rec_avg_intended_air_yds",
    "percent_share_of_intended_air_yards": "ng_rec_pct_share_of_intended_air_yds",
    "receptions": "ng_rec_rec",
    "targets": "ng_rec_targets",
    "catch_percentage": "ng_rec_catch_pct",
    "yards": "ng_rec_yds",
    "rec_touchdowns": "ng_rec_rec_td",
    "avg_yac": "ng_rec_avg_yac",
    "avg_expected_yac": "ng_rec_avg_exp_yac",
    "avg_yac_above_expectation": "ng_rec_avg_yac_above_expectation",
}

NEXTGEN_RUSH_COLUMN_MAP = {
    "season": "season",
    "week": "week",
    "player_display_name": "player_display_name",
    "position": "position",
    "team": "team",
    "player_gsis_id": "ng_rush_player_gsis_id",
    "efficiency": "ng_rush_efficiency",
    "percent_attempts_gte_eight_defenders": "ng_rush_pct_att_gte_eight_defenders",
    "avg_time_to_los": "ng_rush_avg_time_to_los",
    "rush_attempts": "ng_rush_rush_att",
    "rush_yards": "ng_rush_rush_yds",
    "avg_rush_yards": "ng_rush_avg_rush_yds",
    "rush_touchdowns": "ng_rush_rush_td",
    "expected_rush_yards": "ng_rush_exp_rush_yds",
    "rush_yards_over_expected": "ng_rush_rush_yds_over_exp",
    "rush_yards_over_expected_per_att": "ng_rush_rush_yds_over_exp_per_att",
    "rush_pct_over_expected": "ng_rush_rush_pct_over_exp",
}

PFR_PASS_WEEKLY_COLUMN_MAP = {
    "season": "season",
    "week": "week",
    "game_type": "pfr_pass_game_type",
    "game_id": "game_id",
    "pfr_game_id": "pfr_pass_pfr_game_id",
    "team": "team",
    "opponent": "pfr_pass_opponent",
    "player_display_name": "player_display_name",
    "pfr_player_id": "pfr_pass_pfr_player_id",
    "passing_drops": "pfr_pass_passing_drops",
    "passing_drop_pct": "pfr_pass_passing_drop_pct",
    "receiving_drop": "pfr_pass_receiving_drop",
    "receiving_drop_pct": "pfr_pass_receiving_drop_pct",
    "passing_bad_throws": "pfr_pass_passing_bad_throws",
    "passing_bad_throw_pct": "pfr_pass_passing_bad_throw_pct",
    "times_sacked": "pfr_pass_times_sacked",
    "times_blitzed": "pfr_pass_times_blitzed",
    "times_hurried": "pfr_pass_times_hurried",
    "times_hit": "pfr_pass_times_hit",
    "times_pressured": "pfr_pass_times_pressured",
    "times_pressured_pct": "pfr_pass_times_pressured_pct",
    "def_times_blitzed": "pfr_pass_def_times_blitzed",
    "def_times_hurried": "pfr_pass_def_times_hurried",
    "def_times_hitqb": "pfr_pass_def_times_hitqb",
}

PFR_RUSH_WEEKLY_COLUMN_MAP = {
    "season": "season",
    "week": "week",
    "game_type": "pfr_rush_game_type",
    "game_id": "game_id",
    "pfr_game_id": "pfr_rush_pfr_game_id",
    "team": "team",
    "opponent": "pfr_rush_opponent",
    "player_display_name": "player_display_name",
    "pfr_player_id": "pfr_rush_pfr_player_id",
    "carries": "pfr_rush_car",
    "rushing_yards_before_contact": "pfr_rush_rushing_yds_before_contact",
    "rushing_yards_before_contact_avg": "pfr_rush_rushing_yds_before_contact_avg",
    "rushing_yards_after_contact": "pfr_rush_rushing_yds_after_contact",
    "rushing_yards_after_contact_avg": "pfr_rush_rushing_yds_after_contact_avg",
    "rushing_broken_tackles": "pfr_rush_rushing_broken_tackles",
    "receiving_broken_tackles": "pfr_rush_receiving_broken_tackles",
}

PFR_REC_WEEKLY_COLUMN_MAP = {
    "season": "season",
    "week": "week",
    "game_type": "pfr_rec_game_type",
    "game_id": "game_id",
    "pfr_game_id": "pfr_rec_pfr_game_id",
    "team": "team",
    "opponent": "pfr_rec_opponent",
    "player_display_name": "player_display_name",
    "pfr_player_id": "pfr_rec_pfr_player_id",
    "rushing_broken_tackles": "pfr_rec_rushing_broken_tackles",
    "receiving_broken_tackles": "pfr_rec_receiving_broken_tackles",
    "passing_drops": "pfr_rec_passing_drops",
    "passing_drop_pct": "pfr_rec_passing_drop_pct",
    "receiving_drop": "pfr_rec_receiving_drop",
    "receiving_drop_pct": "pfr_rec_receiving_drop_pct",
    "receiving_int": "pfr_rec_receiving_int",
    "receiving_rat": "pfr_rec_receiving_rat",
}

PFR_PASS_SEASON_COLUMN_MAP = {
    "season": "season",
    "player_display_name": "player_display_name",
    "team": "team",
    "pfr_id": "pfr_pass_pfr_id",
    "pass_attempts": "pfr_pass_pass_att",
    "throwaways": "pfr_pass_throwaways",
    "spikes": "pfr_pass_spikes",
    "drops": "pfr_pass_drops",
    "drop_pct": "pfr_pass_drop_pct",
    "bad_throws": "pfr_pass_bad_throws",
    "bad_throw_pct": "pfr_pass_bad_throw_pct",
    "pocket_time": "pfr_pass_pocket_time",
    "times_blitzed": "pfr_pass_times_blitzed",
    "times_hurried": "pfr_pass_times_hurried",
    "times_hit": "pfr_pass_times_hit",
    "times_pressured": "pfr_pass_times_pressured",
    "pressure_pct": "pfr_pass_pressure_pct",
    "batted_balls": "pfr_pass_batted_balls",
    "on_tgt_throws": "pfr_pass_on_tgt_throws",
    "on_tgt_pct": "pfr_pass_on_tgt_pct",
    "rpo_plays": "pfr_pass_rpo_plays",
    "rpo_yards": "pfr_pass_rpo_yds",
    "rpo_pass_att": "pfr_pass_rpo_pass_att",
    "rpo_pass_yards": "pfr_pass_rpo_pass_yds",
    "rpo_rush_att": "pfr_pass_rpo_rush_att",
    "rpo_rush_yards": "pfr_pass_rpo_rush_yds",
    "pa_pass_att": "pfr_pass_pa_pass_att",
    "pa_pass_yards": "pfr_pass_pa_pass_yds",
    "intended_air_yards": "pfr_pass_intended_air_yds",
    "intended_air_yards_per_pass_attempt": "pfr_pass_intended_air_yds_per_pass_att",
    "completed_air_yards": "pfr_pass_completed_air_yds",
    "completed_air_yards_per_completion": "pfr_pass_completed_air_yds_per_cmp",
    "completed_air_yards_per_pass_attempt": "pfr_pass_completed_air_yds_per_pass_att",
    "pass_yards_after_catch": "pfr_pass_pass_yds_after_catch",
    "pass_yards_after_catch_per_completion": "pfr_pass_pass_yds_after_catch_per_cmp",
    "scrambles": "pfr_pass_scrambles",
    "scramble_yards_per_attempt": "pfr_pass_scramble_yds_per_att",
}

PFR_RUSH_SEASON_COLUMN_MAP = {
    "season": "season",
    "player_display_name": "player_display_name",
    "pfr_id": "pfr_rush_pfr_id",
    "team": "team",
    "position": "position",
    "att": "pfr_rush_att",
    "yds": "pfr_rush_yds",
    "td": "pfr_rush_td",
    "x1d": "pfr_rush_x1d",
    "ybc": "pfr_rush_ybc",
    "ybc_att": "pfr_rush_ybc_att",
    "yac": "pfr_rush_yac",
    "yac_att": "pfr_rush_yac_att",
    "brk_tkl": "pfr_rush_brk_tkl",
    "att_br": "pfr_rush_att_br",
}

PFR_REC_SEASON_COLUMN_MAP = {
    "season": "season",
    "player_display_name": "player_display_name",
    "pfr_id": "pfr_rec_pfr_id",
    "team": "team",
    "position": "position",
    "tgt": "pfr_rec_tgt",
    "rec": "pfr_rec_rec",
    "yds": "pfr_rec_yds",
    "td": "pfr_rec_td",
    "x1d": "pfr_rec_x1d",
    "ybc": "pfr_rec_ybc",
    "ybc_r": "pfr_rec_ybc_r",
    "yac": "pfr_rec_yac",
    "yac_r": "pfr_rec_yac_r",
    "adot": "pfr_rec_adot",
    "brk_tkl": "pfr_rec_brk_tkl",
    "rec_br": "pfr_rec_rec_br",
    "drop": "pfr_rec_drop",
    "drop_percent": "pfr_rec_drop_pct",
    "int": "pfr_rec_int",
    "rat": "pfr_rec_rat",
}

SNAP_COUNTS_COLUMN_MAP = {
    "game_id": "game_id",
    "pfr_game_id": "sc_pfr_game_id",
    "season": "season",
    "game_type": "sc_game_type",
    "week": "week",
    "player_display_name": "player_display_name",
    "pfr_player_id": "sc_pfr_player_id",
    "position": "position",
    "team": "team",
    "opponent": "sc_opponent",
    "offense_snaps": "sc_offense_snaps",
    "offense_pct": "sc_offense_pct",
    "defense_snaps": "sc_defense_snaps",
    "defense_pct": "sc_defense_pct",
    "st_snaps": "sc_st_snaps",
    "st_pct": "sc_st_pct",
}

# Interpretation metrics
INTERPRETED_METRIC_SOURCES = {
    "pass_att": ["attempts", "ffo_pass_att", "ng_pass_att", "pfr_pass_pass_att"],
    "pass_yds": ["passing_yards", "ffo_pass_yds_gained", "ng_pass_pass_yds", "pfr_pass_pa_pass_yds"],
    "pass_td": ["passing_tds", "ffo_pass_td", "ng_pass_pass_td"],
    "rush_att": ["carries", "ffo_rush_att", "ng_rush_rush_att", "pfr_rush_att"],
    "rush_yds": ["rushing_yards", "ffo_rush_yds_gained", "ng_rush_rush_yds", "pfr_rush_yds"],
    "rush_td": ["rushing_tds", "ffo_rush_td", "ng_rush_rush_td", "pfr_rush_td"],
    "rec": ["receptions", "ffo_rec", "ng_rec_rec", "pfr_rec_rec"],
    "targets": ["targets", "ng_rec_targets", "pfr_rec_tgt"],
    "rec_yds": ["receiving_yards", "ffo_rec_yds_gained", "ng_rec_yds", "pfr_rec_yds"],
    "rec_td": ["receiving_tds", "ffo_rec_td", "ng_rec_rec_td", "pfr_rec_td"],
    "fp_std": ["fantasy_points", "ffo_total_fp"],
    "fp_ppr": ["fantasy_points_ppr", "ffo_total_fp"],
    "exp_fp": ["ffo_total_fp_exp"],
}

INTERPRETED_PERCENTILE_METRICS = ["fp_ppr", "pass_att", "pass_yds", "rush_att", "rush_yds", "rec_yds", "targets", "exp_fp"]
INTERPRETED_VOLUME_SCORE_METRICS = ["pass_att_pct", "rush_att_pct", "targets_pct"]
