"""Expanded raw-to-normalized column maps for the statistics rework."""

ROSTER_COLUMN_MAP = {
    'birth_date': 'base_birth_date',
    'college': 'base_college',
    'depth_chart_position': 'base_depth_chart_pos',
    'draft_number': 'base_draft_no',
    'draft_club': 'base_draft_team',
    'entry_year': 'base_entry_year',
    'esb_id': 'base_esb_id',
    'espn_id': 'base_espn_id',
    'fantasy_data_id': 'base_fantasy_data_id',
    'first_name': 'base_first_name',
    'football_name': 'base_football_name',
    'game_type': 'base_season_type',
    'gsis_it_id': 'base_gsis_it_id',
    'headshot_url': 'base_headshot_url',
    'height': 'base_height',
    'jersey_number': 'base_jersey_no',
    'last_name': 'base_last_name',
    'ngs_position': 'base_ngs_pos',
    'pff_id': 'base_pff_id',
    'pfr_id': 'base_pfr_id',
    'full_name': 'base_player_display_name',
    'gsis_id': 'base_player_id',
    'position': 'base_pos',
    'rookie_year': 'base_rookie_year',
    'rotowire_id': 'base_rotowire_id',
    'season': 'base_season',
    'sleeper_id': 'base_sleeper_id',
    'smart_id': 'base_smart_id',
    'sportradar_id': 'base_sportradar_id',
    'status': 'base_status',
    'status_description_abbr': 'base_status_desc_abbr',
    'team': 'base_team',
    'week': 'base_week',
    'weight': 'base_weight',
    'yahoo_id': 'base_yahoo_id',
    'years_exp': 'base_years_exp',
}

PLAYER_WEEKLY_COLUMN_MAP = {
    'game_id': 'base_game_id',
    'headshot_url': 'base_headshot_url',
    'opponent_team': 'base_opp_team',
    'player_display_name': 'base_player_display_name',
    'player_id': 'base_player_id',
    'player_name': 'base_player_name',
    'position': 'base_pos',
    'position_group': 'base_pos_group',
    'season': 'base_season',
    'season_type': 'base_season_type',
    'team': 'base_team',
    'week': 'base_week',
    'passing_first_downs': 'pass_1st',
    'passing_2pt_conversions': 'pass_2pt',
    'passing_air_yards': 'pass_air_yds',
    'attempts': 'pass_att',
    'completions': 'pass_comp',
    'passing_cpoe': 'pass_cpoe',
    'passing_epa': 'pass_epa',
    'passing_interceptions': 'pass_ints',
    'pacr': 'pass_pacr',
    'sack_fumbles': 'pass_sac_fums',
    'sack_fumbles_lost': 'pass_sac_fums_lost',
    'sack_yards_lost': 'pass_sac_yds_lost',
    'sacks_suffered': 'pass_sacks',
    'passing_tds': 'pass_tds',
    'passing_yards_after_catch': 'pass_yac',
    'passing_yards': 'pass_yds',
    'rushing_first_downs': 'rush_1st',
    'rushing_2pt_conversions': 'rush_2pt',
    'carries': 'rush_att',
    'rushing_epa': 'rush_epa',
    'rushing_fumbles': 'rush_fums',
    'rushing_fumbles_lost': 'rush_fums_lost',
    'rushing_tds': 'rush_tds',
    'rushing_yards': 'rush_yds',
    'receiving_first_downs': 'rec_1st',
    'receiving_2pt_conversions': 'rec_2pt',
    'receiving_air_yards': 'rec_air_yds',
    'air_yards_share': 'rec_air_yds_share',
    'receiving_epa': 'rec_epa',
    'receiving_fumbles': 'rec_fums',
    'receiving_fumbles_lost': 'rec_fums_lost',
    'racr': 'rec_racr',
    'receptions': 'rec_recs',
    'receiving_tds': 'rec_tds',
    'target_share': 'rec_tgt_share',
    'targets': 'rec_tgts',
    'wopr': 'rec_wopr',
    'receiving_yards_after_catch': 'rec_yac',
    'receiving_yards': 'rec_yds',
    'fantasy_points_ppr': 'fantasy_fp_ppr',
    'fantasy_points': 'fantasy_fp_std',
    'kickoff_return_yards': 'spec_kick_ret_yds',
    'kickoff_returns': 'spec_kick_rets',
    'punt_return_yards': 'spec_punt_ret_yds',
    'punt_returns': 'spec_punt_rets',
    'special_teams_tds': 'spec_tds',
    'fumble_recovery_opp': 'misc_fum_rec_opp',
    'fumble_recovery_yards_opp': 'misc_fum_rec_opp_yds',
    'fumble_recovery_own': 'misc_fum_rec_own',
    'fumble_recovery_yards_own': 'misc_fum_rec_own_yds',
    'fumble_recovery_tds': 'misc_fum_rec_tds',
    'penalty_yards': 'misc_pen_yds',
    'penalties': 'misc_pens',
    'misc_yards': 'misc_yds',
    'fg_att': 'kick_fg_att',
    'fg_blocked': 'kick_fg_blocked',
    'fg_blocked_distance': 'kick_fg_blocked_dist',
    'fg_blocked_list': 'kick_fg_blocked_list',
    'fg_long': 'kick_fg_long',
    'fg_made': 'kick_fg_made',
    'fg_made_0_19': 'kick_fg_made_0_19',
    'fg_made_20_29': 'kick_fg_made_20_29',
    'fg_made_30_39': 'kick_fg_made_30_39',
    'fg_made_40_49': 'kick_fg_made_40_49',
    'fg_made_50_59': 'kick_fg_made_50_59',
    'fg_made_60_': 'kick_fg_made_60_plus',
    'fg_made_distance': 'kick_fg_made_dist',
    'fg_made_list': 'kick_fg_made_list',
    'fg_missed': 'kick_fg_missed',
    'fg_missed_0_19': 'kick_fg_missed_0_19',
    'fg_missed_20_29': 'kick_fg_missed_20_29',
    'fg_missed_30_39': 'kick_fg_missed_30_39',
    'fg_missed_40_49': 'kick_fg_missed_40_49',
    'fg_missed_50_59': 'kick_fg_missed_50_59',
    'fg_missed_60_': 'kick_fg_missed_60_plus',
    'fg_missed_distance': 'kick_fg_missed_dist',
    'fg_missed_list': 'kick_fg_missed_list',
    'fg_pct': 'kick_fg_pct',
    'gwfg_att': 'kick_gwfg_att',
    'gwfg_blocked': 'kick_gwfg_blocked',
    'gwfg_distance': 'kick_gwfg_dist',
    'gwfg_made': 'kick_gwfg_made',
    'gwfg_missed': 'kick_gwfg_missed',
    'pat_att': 'kick_pat_att',
    'pat_blocked': 'kick_pat_blocked',
    'pat_made': 'kick_pat_made',
    'pat_missed': 'kick_pat_missed',
    'pat_pct': 'kick_pat_pct',
}

PLAYER_SEASONAL_COLUMN_MAP = {
    'games': 'base_games',
    'headshot_url': 'base_headshot_url',
    'player_display_name': 'base_player_display_name',
    'player_id': 'base_player_id',
    'player_name': 'base_player_name',
    'position': 'base_pos',
    'position_group': 'base_pos_group',
    'season': 'base_season',
    'season_type': 'base_season_type',
    'recent_team': 'base_team',
    'passing_first_downs': 'pass_1st',
    'passing_2pt_conversions': 'pass_2pt',
    'passing_air_yards': 'pass_air_yds',
    'attempts': 'pass_att',
    'completions': 'pass_comp',
    'passing_cpoe': 'pass_cpoe',
    'passing_epa': 'pass_epa',
    'passing_interceptions': 'pass_ints',
    'pacr': 'pass_pacr',
    'sack_fumbles': 'pass_sac_fums',
    'sack_fumbles_lost': 'pass_sac_fums_lost',
    'sack_yards_lost': 'pass_sac_yds_lost',
    'sacks_suffered': 'pass_sacks',
    'passing_tds': 'pass_tds',
    'passing_yards_after_catch': 'pass_yac',
    'passing_yards': 'pass_yds',
    'rushing_first_downs': 'rush_1st',
    'rushing_2pt_conversions': 'rush_2pt',
    'carries': 'rush_att',
    'rushing_epa': 'rush_epa',
    'rushing_fumbles': 'rush_fums',
    'rushing_fumbles_lost': 'rush_fums_lost',
    'rushing_tds': 'rush_tds',
    'rushing_yards': 'rush_yds',
    'receiving_first_downs': 'rec_1st',
    'receiving_2pt_conversions': 'rec_2pt',
    'receiving_air_yards': 'rec_air_yds',
    'air_yards_share': 'rec_air_yds_share',
    'receiving_epa': 'rec_epa',
    'receiving_fumbles': 'rec_fums',
    'receiving_fumbles_lost': 'rec_fums_lost',
    'racr': 'rec_racr',
    'receptions': 'rec_recs',
    'receiving_tds': 'rec_tds',
    'target_share': 'rec_tgt_share',
    'targets': 'rec_tgts',
    'wopr': 'rec_wopr',
    'receiving_yards_after_catch': 'rec_yac',
    'receiving_yards': 'rec_yds',
    'fantasy_points_ppr': 'fantasy_fp_ppr',
    'fantasy_points': 'fantasy_fp_std',
    'kickoff_return_yards': 'spec_kick_ret_yds',
    'kickoff_returns': 'spec_kick_rets',
    'punt_return_yards': 'spec_punt_ret_yds',
    'punt_returns': 'spec_punt_rets',
    'special_teams_tds': 'spec_tds',
    'fumble_recovery_opp': 'misc_fum_rec_opp',
    'fumble_recovery_yards_opp': 'misc_fum_rec_opp_yds',
    'fumble_recovery_own': 'misc_fum_rec_own',
    'fumble_recovery_yards_own': 'misc_fum_rec_own_yds',
    'fumble_recovery_tds': 'misc_fum_rec_tds',
    'penalty_yards': 'misc_pen_yds',
    'penalties': 'misc_pens',
    'misc_yards': 'misc_yds',
    'fg_att': 'kick_fg_att',
    'fg_blocked': 'kick_fg_blocked',
    'fg_blocked_distance': 'kick_fg_blocked_dist',
    'fg_blocked_list': 'kick_fg_blocked_list',
    'fg_long': 'kick_fg_long',
    'fg_made': 'kick_fg_made',
    'fg_made_0_19': 'kick_fg_made_0_19',
    'fg_made_20_29': 'kick_fg_made_20_29',
    'fg_made_30_39': 'kick_fg_made_30_39',
    'fg_made_40_49': 'kick_fg_made_40_49',
    'fg_made_50_59': 'kick_fg_made_50_59',
    'fg_made_60_': 'kick_fg_made_60_plus',
    'fg_made_distance': 'kick_fg_made_dist',
    'fg_made_list': 'kick_fg_made_list',
    'fg_missed': 'kick_fg_missed',
    'fg_missed_0_19': 'kick_fg_missed_0_19',
    'fg_missed_20_29': 'kick_fg_missed_20_29',
    'fg_missed_30_39': 'kick_fg_missed_30_39',
    'fg_missed_40_49': 'kick_fg_missed_40_49',
    'fg_missed_50_59': 'kick_fg_missed_50_59',
    'fg_missed_60_': 'kick_fg_missed_60_plus',
    'fg_missed_distance': 'kick_fg_missed_dist',
    'fg_missed_list': 'kick_fg_missed_list',
    'fg_pct': 'kick_fg_pct',
    'gwfg_att': 'kick_gwfg_att',
    'gwfg_blocked': 'kick_gwfg_blocked',
    'gwfg_distance_list': 'kick_gwfg_dist_list',
    'gwfg_made': 'kick_gwfg_made',
    'gwfg_missed': 'kick_gwfg_missed',
    'pat_att': 'kick_pat_att',
    'pat_blocked': 'kick_pat_blocked',
    'pat_made': 'kick_pat_made',
    'pat_missed': 'kick_pat_missed',
    'pat_pct': 'kick_pat_pct',
}

FF_OPPORTUNITY_WEEKLY_COLUMN_MAP = {
    'game_id': 'base_game_id',
    'full_name': 'base_player_display_name',
    'player_id': 'base_player_id',
    'position': 'base_pos',
    'season': 'base_season',
    'posteam': 'base_team',
    'week': 'base_week',
    'pass_first_down': 'pass_1st',
    'pass_first_down_diff': 'pass_1st_diff',
    'pass_first_down_exp': 'pass_1st_exp',
    'pass_two_point_conv': 'pass_2pt',
    'pass_two_point_conv_diff': 'pass_2pt_diff',
    'pass_two_point_conv_exp': 'pass_2pt_exp',
    'pass_air_yards': 'pass_air_yds',
    'pass_attempt': 'pass_att',
    'pass_completions': 'pass_comp',
    'pass_completions_diff': 'pass_comp_diff',
    'pass_completions_exp': 'pass_comp_exp',
    'pass_fantasy_points': 'pass_fp_std',
    'pass_fantasy_points_diff': 'pass_fp_std_diff',
    'pass_fantasy_points_exp': 'pass_fp_std_exp',
    'pass_interception': 'pass_ints',
    'pass_interception_diff': 'pass_ints_diff',
    'pass_interception_exp': 'pass_ints_exp',
    'pass_touchdown': 'pass_tds',
    'pass_touchdown_diff': 'pass_tds_diff',
    'pass_touchdown_exp': 'pass_tds_exp',
    'pass_yards_gained': 'pass_yds',
    'pass_yards_gained_diff': 'pass_yds_diff',
    'pass_yards_gained_exp': 'pass_yds_exp',
    'rush_first_down': 'rush_1st',
    'rush_first_down_diff': 'rush_1st_diff',
    'rush_first_down_exp': 'rush_1st_exp',
    'rush_two_point_conv': 'rush_2pt',
    'rush_two_point_conv_diff': 'rush_2pt_diff',
    'rush_two_point_conv_exp': 'rush_2pt_exp',
    'rush_attempt': 'rush_att',
    'rush_fantasy_points': 'rush_fp_std',
    'rush_fantasy_points_diff': 'rush_fp_std_diff',
    'rush_fantasy_points_exp': 'rush_fp_std_exp',
    'rush_fumble_lost': 'rush_fums_lost',
    'rush_touchdown': 'rush_tds',
    'rush_touchdown_diff': 'rush_tds_diff',
    'rush_touchdown_exp': 'rush_tds_exp',
    'rush_yards_gained': 'rush_yds',
    'rush_yards_gained_diff': 'rush_yds_diff',
    'rush_yards_gained_exp': 'rush_yds_exp',
    'rec_first_down': 'rec_1st',
    'rec_first_down_diff': 'rec_1st_diff',
    'rec_first_down_exp': 'rec_1st_exp',
    'rec_two_point_conv': 'rec_2pt',
    'rec_two_point_conv_diff': 'rec_2pt_diff',
    'rec_two_point_conv_exp': 'rec_2pt_exp',
    'rec_air_yards': 'rec_air_yds',
    'rec_fantasy_points': 'rec_fp_ppr',
    'rec_fantasy_points_diff': 'rec_fp_ppr_diff',
    'rec_fantasy_points_exp': 'rec_fp_ppr_exp',
    'rec_fumble_lost': 'rec_fums_lost',
    'rec_interception': 'rec_tgt_ints',
    'rec_interception_diff': 'rec_tgt_ints_diff',
    'rec_interception_exp': 'rec_tgt_ints_exp',
    'receptions': 'rec_recs',
    'receptions_diff': 'rec_recs_diff',
    'receptions_exp': 'rec_recs_exp',
    'rec_touchdown': 'rec_tds',
    'rec_touchdown_diff': 'rec_tds_diff',
    'rec_touchdown_exp': 'rec_tds_exp',
    'rec_attempt': 'rec_tgts',
    'rec_yards_gained': 'rec_yds',
    'rec_yards_gained_diff': 'rec_yds_diff',
    'rec_yards_gained_exp': 'rec_yds_exp',
    'total_fantasy_points': 'fantasy_fp_ppr',
    'total_fantasy_points_diff': 'fantasy_fp_ppr_diff',
    'total_fantasy_points_exp': 'fantasy_fp_ppr_exp',
    'total_first_down': 'total_1st',
    'total_first_down_diff': 'total_1st_diff',
    'total_first_down_exp': 'total_1st_exp',
    'total_touchdown': 'total_tds',
    'total_touchdown_diff': 'total_tds_diff',
    'total_touchdown_exp': 'total_tds_exp',
    'total_yards_gained': 'total_yds',
    'total_yards_gained_diff': 'total_yds_diff',
    'total_yards_gained_exp': 'total_yds_exp',
}

NEXTGEN_PASS_COLUMN_MAP = {
    'player_first_name': 'base_first_name',
    'player_jersey_number': 'base_jersey_no',
    'player_last_name': 'base_last_name',
    'player_display_name': 'base_player_display_name',
    'player_gsis_id': 'base_player_id',
    'player_position': 'base_pos',
    'season': 'base_season',
    'season_type': 'base_season_type',
    'player_short_name': 'base_short_name',
    'team_abbr': 'base_team',
    'week': 'base_week',
    'aggressiveness': 'pass_aggressiveness',
    'attempts': 'pass_att',
    'avg_air_distance': 'pass_avg_air_dist',
    'avg_air_yards_differential': 'pass_avg_air_yds_diff',
    'avg_air_yards_to_sticks': 'pass_avg_air_yds_to_sticks',
    'avg_time_to_throw': 'pass_avg_time_to_throw',
    'completions': 'pass_comp',
    'completion_percentage': 'pass_comp_pct',
    'expected_completion_percentage': 'pass_comp_pct_exp',
    'avg_completed_air_yards': 'pass_avg_comp_air_yds',
    'completion_percentage_above_expectation': 'pass_cpoe',
    'avg_intended_air_yards': 'pass_avg_intended_air_yds',
    'interceptions': 'pass_ints',
    'max_air_distance': 'pass_max_air_dist',
    'max_completed_air_distance': 'pass_max_completed_air_dist',
    'passer_rating': 'pass_rating',
    'pass_touchdowns': 'pass_tds',
    'pass_yards': 'pass_yds',
}

NEXTGEN_REC_COLUMN_MAP = {
    'player_first_name': 'base_first_name',
    'player_jersey_number': 'base_jersey_no',
    'player_last_name': 'base_last_name',
    'player_display_name': 'base_player_display_name',
    'player_gsis_id': 'base_player_id',
    'player_position': 'base_pos',
    'season': 'base_season',
    'season_type': 'base_season_type',
    'player_short_name': 'base_short_name',
    'team_abbr': 'base_team',
    'week': 'base_week',
    'avg_intended_air_yards': 'rec_avg_intended_air_yds',
    'percent_share_of_intended_air_yards': 'rec_air_yds_share_pct',
    'avg_cushion': 'rec_avg_cushion',
    'avg_separation': 'rec_avg_sep',
    'catch_percentage': 'rec_catch_pct',
    'receptions': 'rec_recs',
    'rec_touchdowns': 'rec_tds',
    'targets': 'rec_tgts',
    'avg_yac': 'rec_avg_yac',
    'avg_yac_above_expectation': 'rec_avg_yac_above_exp',
    'avg_expected_yac': 'rec_avg_yac_exp',
    'yards': 'rec_yds',
}

NEXTGEN_RUSH_COLUMN_MAP = {
    'player_first_name': 'base_first_name',
    'player_jersey_number': 'base_jersey_no',
    'player_last_name': 'base_last_name',
    'player_display_name': 'base_player_display_name',
    'player_gsis_id': 'base_player_id',
    'player_position': 'base_pos',
    'season': 'base_season',
    'season_type': 'base_season_type',
    'player_short_name': 'base_short_name',
    'team_abbr': 'base_team',
    'week': 'base_week',
    'rush_attempts': 'rush_att',
    'percent_attempts_gte_eight_defenders': 'rush_att_gte_eight_def_pct',
    'avg_time_to_los': 'rush_avg_time_to_los',
    'efficiency': 'rush_efficiency',
    'rush_pct_over_expected': 'rush_pct_over_exp',
    'rush_touchdowns': 'rush_tds',
    'rush_yards': 'rush_yds',
    'expected_rush_yards': 'rush_yds_exp',
    'rush_yards_over_expected': 'rush_yds_over_exp',
    'rush_yards_over_expected_per_att': 'rush_yds_over_exp_per_att',
    'avg_rush_yards': 'rush_avg_yds',
}

PFR_PASS_WEEKLY_COLUMN_MAP = {
    'game_id': 'base_game_id',
    'game_type': 'base_season_type',
    'opponent': 'base_opp_team',
    'pfr_game_id': 'base_pfr_game_id',
    'pfr_player_id': 'base_pfr_id',
    'pfr_player_name': 'base_player_display_name',
    'season': 'base_season',
    'team': 'base_team',
    'week': 'base_week',
    'passing_bad_throw_pct': 'pass_bad_throw_pct',
    'passing_bad_throws': 'pass_bad_throws',
    'passing_drop_pct': 'pass_drop_pct',
    'passing_drops': 'pass_drops',
    'times_pressured_pct': 'pass_pressure_pct',
    'times_hit': 'pass_qb_hits',
    'times_sacked': 'pass_sacks',
    'times_blitzed': 'pass_times_blitzed',
    'times_hurried': 'pass_times_hurried',
    'times_pressured': 'pass_times_pressured',
}

PFR_RUSH_WEEKLY_COLUMN_MAP = {
    'game_id': 'base_game_id',
    'game_type': 'base_season_type',
    'opponent': 'base_opp_team',
    'pfr_game_id': 'base_pfr_game_id',
    'pfr_player_id': 'base_pfr_id',
    'pfr_player_name': 'base_player_display_name',
    'season': 'base_season',
    'team': 'base_team',
    'week': 'base_week',
    'carries': 'rush_att',
    'rushing_broken_tackles': 'rush_brk_tkls',
    'rushing_yards_after_contact': 'rush_yac',
    'rushing_yards_after_contact_avg': 'rush_yac_per_att',
    'rushing_yards_before_contact_avg': 'rush_ybc_per_att',
    'rushing_yards_before_contact': 'rush_ybc_yds',
}

PFR_REC_WEEKLY_COLUMN_MAP = {
    'game_id': 'base_game_id',
    'game_type': 'base_season_type',
    'opponent': 'base_opp_team',
    'pfr_game_id': 'base_pfr_game_id',
    'pfr_player_id': 'base_pfr_id',
    'pfr_player_name': 'base_player_display_name',
    'season': 'base_season',
    'team': 'base_team',
    'week': 'base_week',
    'receiving_broken_tackles': 'rec_brk_tkls',
    'receiving_drop_pct': 'rec_drop_pct',
    'receiving_drop': 'rec_drops',
    'receiving_int': 'rec_tgt_ints',
    'receiving_rat': 'rec_tgt_rating',
}

PFR_PASS_SEASON_COLUMN_MAP = {
    'pfr_id': 'base_pfr_id',
    'player': 'base_player_display_name',
    'season': 'base_season',
    'team': 'base_team',
    'pass_attempts': 'pass_att',
    'bad_throw_pct': 'pass_bad_throw_pct',
    'bad_throws': 'pass_bad_throws',
    'batted_balls': 'pass_batted_balls',
    'completed_air_yards': 'pass_completed_air_yds',
    'completed_air_yards_per_pass_attempt': 'pass_completed_air_yds_per_att',
    'completed_air_yards_per_completion': 'pass_completed_air_yds_per_comp',
    'drop_pct': 'pass_drop_pct',
    'drops': 'pass_drops',
    'intended_air_yards': 'pass_intended_air_yds',
    'intended_air_yards_per_pass_attempt': 'pass_intended_air_yds_per_att',
    'on_tgt_pct': 'pass_on_tgt_pct',
    'on_tgt_throws': 'pass_on_tgt_throws',
    'pocket_time': 'pass_pocket_time',
    'pressure_pct': 'pass_pressure_pct',
    'times_hit': 'pass_qb_hits',
    'rpo_pass_att': 'pass_rpo_pass_att',
    'rpo_pass_yards': 'pass_rpo_pass_yds',
    'rpo_plays': 'pass_rpo_plays',
    'rpo_yards': 'pass_rpo_yds',
    'scramble_yards_per_attempt': 'pass_scramble_yds_per_att',
    'scrambles': 'pass_scrambles',
    'spikes': 'pass_spikes',
    'throwaways': 'pass_throwaways',
    'times_blitzed': 'pass_times_blitzed',
    'times_hurried': 'pass_times_hurried',
    'times_pressured': 'pass_times_pressured',
    'pass_yards_after_catch': 'pass_yac',
    'pass_yards_after_catch_per_completion': 'pass_yac_per_comp',
    'rpo_rush_att': 'rush_rpo_att',
    'rpo_rush_yards': 'rush_rpo_yds',
}

PFR_RUSH_SEASON_COLUMN_MAP = {
    'age': 'base_age',
    'g': 'base_games',
    'gs': 'base_games_started',
    'loaded': 'base_loaded_at',
    'pfr_id': 'base_pfr_id',
    'player': 'base_player_display_name',
    'pos': 'base_pos',
    'season': 'base_season',
    'tm': 'base_team',
    'x1d': 'rush_1st',
    'att': 'rush_att',
    'att_br': 'rush_att_per_brk_tkl',
    'brk_tkl': 'rush_brk_tkls',
    'yac': 'rush_yac',
    'yac_att': 'rush_yac_per_att',
    'ybc_att': 'rush_ybc_per_att',
    'ybc': 'rush_ybc_yds',
    'yds': 'rush_yds',
}

PFR_REC_SEASON_COLUMN_MAP = {
    'age': 'base_age',
    'g': 'base_games',
    'gs': 'base_games_started',
    'loaded': 'base_loaded_at',
    'pfr_id': 'base_pfr_id',
    'player': 'base_player_display_name',
    'pos': 'base_pos',
    'season': 'base_season',
    'tm': 'base_team',
    'x1d': 'rec_1st',
    'adot': 'rec_adot',
    'brk_tkl': 'rec_brk_tkls',
    'drop_percent': 'rec_drop_pct',
    'drop': 'rec_drops',
    'int': 'rec_tgt_ints',
    'rat': 'rec_tgt_rating',
    'rec_br': 'rec_recs_per_brk_tkl',
    'rec': 'rec_recs',
    'tgt': 'rec_tgts',
    'yac': 'rec_yac',
    'yac_r': 'rec_yac_per_rec',
    'ybc_r': 'rec_ybc_per_rec',
    'ybc': 'rec_ybc_yds',
    'yds': 'rec_yds',
}

SNAP_COUNTS_COLUMN_MAP = {
    'game_id': 'base_game_id',
    'game_type': 'base_season_type',
    'opponent': 'base_opp_team',
    'pfr_game_id': 'base_pfr_game_id',
    'pfr_player_id': 'base_pfr_id',
    'player': 'base_player_display_name',
    'position': 'base_pos',
    'season': 'base_season',
    'team': 'base_team',
    'week': 'base_week',
    'offense_snaps': 'snap_off',
    'offense_pct': 'snap_off_pct',
    'st_snaps': 'snap_spec',
    'st_pct': 'snap_spec_pct',
}

PFR_NAME_MAP = {
    "A.J. McCarron": "AJ McCarron",
    "AJ Brown": "A.J. Brown",
    "AJ Derby": "A.J. Derby",
    "AJ Green": "A.J. Green",
    "AT Perry": "A.T. Perry",
    "Adrian Killins": "Adrian Killins Jr.",
    "Aidan OConnell": "Aidan O'Connell",
    "Amon-Ra St Brown": "Amon-Ra St. Brown",
    "Anthony McFarland Jr.": "Anthony McFarland",
    "Ben Watson": "Benjamin Watson",
    "Benny Snell Jr.": "Benny Snell",
    "Brian Robinson Jr.": "Brian Robinson",
    "Brian Thomas": "Brian Thomas Jr.",
    "CJ Anderson": "C.J. Anderson",
    "CJ Beathard": "C.J. Beathard",
    "CJ Board": "C.J. Board",
    "CJ Prosise": "C.J. Prosise",
    "CJ Saunders": "C.J. Saunders",
    "CJ Stroud": "C.J. Stroud",
    "CJ Uzomah": "C.J. Uzomah",
    "Calvin Austin": "Calvin Austin III",
    "Cam Batson": "Cameron Batson",
    "Cedrick Wilson": "Cedrick Wilson Jr.",
    "Chigoziem Okonkwo": "Chig Okonkwo",
    "Chris Godwin": "Chris Godwin Jr.",
    "Chris Rodriguez": "Chris Rodriguez Jr.",
    "D.J. Moore": "DJ Moore",
    "D.K. Metcalf": "DK Metcalf",
    "DAndre Swift": "D'Andre Swift",
    "DErnest Johnson": "D'Ernest Johnson",
    "DJ Foster": "D.J. Foster",
    "DJ Montgomery": "D.J. Montgomery",
    "DOnta Foreman": "D'Onta Foreman",
    "DWayne Eskridge": "Dee Eskridge",
    "DaMari Scott": "Da'Mari Scott",
    "David Sills V": "David Sills",
    "De'Angelo Henderson": "De'Angelo Henderson Sr.",
    "DeAngelo Henderson": "De'Angelo Henderson Sr.",
    "DeAnthony Thomas": "De'Anthony Thomas",
    "DeLance Turner": "De'Lance Turner",
    "DeMichael Harris": "De'Michael Harris",
    "DeVon Achane": "De'Von Achane",
    "Deebo Samuel": "Deebo Samuel Sr.",
    "Demario Douglas": "DeMario Douglas",
    "Dont'e Thornton": "Dont'e Thornton Jr.",
    "Donte Thornton": "Dont'e Thornton Jr.",
    "EJ Jenkins": "E.J. Jenkins",
    "Efton Chism": "Efton Chism III",
    "Equanimeous St Brown": "Equanimeous St. Brown",
    "Gabriel Davis": "Gabe Davis",
    "Gardner Minshew II": "Gardner Minshew",
    "Grant Dubose": "Grant DuBose",
    "Harold Fannin": "Harold Fannin Jr.",
    "Henry Ruggs": "Henry Ruggs III",
    "Irv Smith Jr.": "Irv Smith",
    "JD McKissic": "J.D. McKissic",
    "JJ Arcega-Whiteside": "J.J. Arcega-Whiteside",
    "JJ Jones": "J.J. Jones",
    "JJ McCarthy": "J.J. McCarthy",
    "JJ Nelson": "J.J. Nelson",
    "JJ Taylor": "J.J. Taylor",
    "JK Dobbins": "J.K. Dobbins",
    "JMon Moore": "J'Mon Moore",
    "JP Holtz": "J.P. Holtz",
    "JaLynn Polk": "Ja'Lynn Polk",
    "JaMarcus Bradley": "Ja'Marcus Bradley",
    "JaMarr Chase": "Ja'Marr Chase",
    "JaTavion Sanders": "Ja'Tavion Sanders",
    "James OShaughnessy": "James O'Shaughnessy",
    "Jamycal Hasty": "JaMycal Hasty",
    "JhaQuan Jackson": "Jha'Quan Jackson",
    "Jimmy Horn": "Jimmy Horn Jr.",
    "Joe Milton": "Joe Milton III",
    "John Metchie": "John Metchie III",
    "John Samuel Shenker": "John Shenker",
    "Jojo Natson": "JoJo Natson",
    "Joshua Perkins": "Josh Perkins",
    "KJ Osborn": "K.J. Osborn",
    "KeShawn Vaughn": "Ke'Shawn Vaughn",
    "KeShawn Williams": "Ke'Shawn Williams",
    "Kenneth Walker": "Kenneth Walker III",
    "Kerrith Whyte Jr": "Kerrith Whyte",
    "Kevin Austin": "Kevin Austin Jr.",
    "Kwamie Lassiter": "Kwamie Lassiter II",
    "LaMical Perine": "La'Mical Perine",
    "Larry Rountree": "Larry Rountree III",
    "Laviska Shenault": "Laviska Shenault Jr.",
    "LeQuint Allen": "LeQuint Allen Jr.",
    "LeVante Bellamy": "Levante Bellamy",
    "LeVeon Bell": "Le'Veon Bell",
    "LilJordan Humphrey": "Lil'Jordan Humphrey",
    "Luther Burden": "Luther Burden III",
    "Lynn Bowden Jr.": "Lynn Bowden",
    "Marvin Harrison": "Marvin Harrison Jr.",
    "Marvin Mims": "Marvin Mims Jr.",
    "Michael Penix": "Michael Penix Jr.",
    "Michael Pittman Jr.": "Michael Pittman",
    "NKeal Harry": "N'Keal Harry",
    "Nick OLeary": "Nick O'Leary",
    "OJ Howard": "O.J. Howard",
    "Odell Beckham": "Odell Beckham Jr.",
    "Olabisi Johnson": "Bisi Johnson",
    "Ollie Gordon": "Ollie Gordon II",
    "Oronde Gadsden": "Oronde Gadsden II",
    "P.J. Walker": "PJ Walker",
    "Robert Griffin": "Robert Griffin III",
    "Ronald Jones II": "Ronald Jones",
    "Rodney Williams": "Rod Williams",
    "Seth Devalve": "Seth DeValve",
    "Stanley Morgan Jr.": "Stanley Morgan",
    "TJ Hockenson": "T.J. Hockenson",
    "TJ Jones": "T.J. Jones",
    "TJ Yeldon": "T.J. Yeldon",
    "TY Hilton": "T.Y. Hilton",
    "Ted Ginn Jr.": "Ted Ginn",
    "Terrace Marshall": "Terrace Marshall Jr.",
    "Theo Wease": "Theo Wease Jr.",
    "Tre McKitty": "Tre' McKitty",
    "TreQuan Smith": "Tre'Quan Smith",
    "TySon Williams": "Ty'Son Williams",
    "Tyrone Tracy": "Tyrone Tracy Jr.",
    "Ulysses Bentley": "Ulysses Bentley IV",
    "Velus Jones": "Velus Jones Jr.",
    "WanDale Robinson": "Wan'Dale Robinson",
}

ROSTER_REQUIRED_COLUMNS = ['base_player_display_name', 'base_season', 'base_pos', 'base_birth_date', 'base_headshot_url', 'base_status', 'base_team', 'base_entry_year']
PLAYER_WEEKLY_REQUIRED_COLUMNS = ['base_season', 'base_week', 'base_game_id', 'base_player_id', 'base_player_display_name', 'base_pos', 'base_team']
PLAYER_SEASONAL_REQUIRED_COLUMNS = ['base_season', 'base_player_id', 'base_player_display_name', 'base_pos', 'base_team']
FF_OPPORTUNITY_WEEKLY_REQUIRED_COLUMNS = ['base_season', 'base_week', 'base_player_id', 'base_player_display_name', 'base_pos', 'base_team']
NEXTGEN_PASS_REQUIRED_COLUMNS = ['base_season', 'base_week', 'base_player_display_name', 'base_pos', 'base_team']
NEXTGEN_REC_REQUIRED_COLUMNS = ['base_season', 'base_week', 'base_player_display_name', 'base_pos', 'base_team']
NEXTGEN_RUSH_REQUIRED_COLUMNS = ['base_season', 'base_week', 'base_player_display_name', 'base_pos', 'base_team']
PFR_PASS_WEEKLY_REQUIRED_COLUMNS = ['base_season', 'base_week', 'base_game_id', 'base_player_display_name', 'base_team']
PFR_RUSH_WEEKLY_REQUIRED_COLUMNS = ['base_season', 'base_week', 'base_game_id', 'base_player_display_name', 'base_team']
PFR_REC_WEEKLY_REQUIRED_COLUMNS = ['base_season', 'base_week', 'base_game_id', 'base_player_display_name', 'base_team']
PFR_PASS_SEASON_REQUIRED_COLUMNS = ['base_season', 'base_player_display_name', 'base_team']
PFR_RUSH_SEASON_REQUIRED_COLUMNS = ['base_season', 'base_player_display_name', 'base_pos']
PFR_REC_SEASON_REQUIRED_COLUMNS = ['base_season', 'base_player_display_name', 'base_pos']
SNAP_COUNTS_REQUIRED_COLUMNS = ['base_season', 'base_week', 'base_player_display_name', 'base_pos', 'base_team']

REQUIRED_COLUMNS = {
    'rosters': ROSTER_REQUIRED_COLUMNS,
    'player_weekly': PLAYER_WEEKLY_REQUIRED_COLUMNS,
    'player_seasonal': PLAYER_SEASONAL_REQUIRED_COLUMNS,
    'ff_opp_weekly': FF_OPPORTUNITY_WEEKLY_REQUIRED_COLUMNS,
    'nextgen_pass_weekly': NEXTGEN_PASS_REQUIRED_COLUMNS,
    'nextgen_rec_weekly': NEXTGEN_REC_REQUIRED_COLUMNS,
    'nextgen_rush_weekly': NEXTGEN_RUSH_REQUIRED_COLUMNS,
    'pfr_pass_weekly': PFR_PASS_WEEKLY_REQUIRED_COLUMNS,
    'pfr_rush_weekly': PFR_RUSH_WEEKLY_REQUIRED_COLUMNS,
    'pfr_rec_weekly': PFR_REC_WEEKLY_REQUIRED_COLUMNS,
    'pfr_pass_season': PFR_PASS_SEASON_REQUIRED_COLUMNS,
    'pfr_rush_season': PFR_RUSH_SEASON_REQUIRED_COLUMNS,
    'pfr_rec_season': PFR_REC_SEASON_REQUIRED_COLUMNS,
    'snap_counts': SNAP_COUNTS_REQUIRED_COLUMNS,
}

COLUMN_MAPS = {
    'rosters': ROSTER_COLUMN_MAP,
    'player_weekly': PLAYER_WEEKLY_COLUMN_MAP,
    'player_seasonal': PLAYER_SEASONAL_COLUMN_MAP,
    'ff_opp_weekly': FF_OPPORTUNITY_WEEKLY_COLUMN_MAP,
    'nextgen_pass_weekly': NEXTGEN_PASS_COLUMN_MAP,
    'nextgen_rec_weekly': NEXTGEN_REC_COLUMN_MAP,
    'nextgen_rush_weekly': NEXTGEN_RUSH_COLUMN_MAP,
    'pfr_pass_weekly': PFR_PASS_WEEKLY_COLUMN_MAP,
    'pfr_rush_weekly': PFR_RUSH_WEEKLY_COLUMN_MAP,
    'pfr_rec_weekly': PFR_REC_WEEKLY_COLUMN_MAP,
    'pfr_pass_season': PFR_PASS_SEASON_COLUMN_MAP,
    'pfr_rush_season': PFR_RUSH_SEASON_COLUMN_MAP,
    'pfr_rec_season': PFR_REC_SEASON_COLUMN_MAP,
    'snap_counts': SNAP_COUNTS_COLUMN_MAP,
}
